### PR TITLE
Fix delete tunnel

### PR DESCRIPTION
**Pull request by gvas**
To delete a tunnel, Sauce Labs' REST API expects an id which is different from the tunnel-identifier specified as the -i parameter of Sauce Connect.
Also fixed the SAUCE_ACCESS_KEY environment variable in the test file.

### CODE REVIEW

**Comment by woollybogger** [comment]
"Fixing" the `SAUCE_ACCESS_KEY` environment variable will not actually be helpful if it has been exported (or saved in the `.travis.yml` file) as something else (e.g. `SAUCE_ACCESSKEY`).

The Sauce Labs documentation says to use `SAUCE_ACCESS_KEY` as the environment variable, but it technically can be anything. That being said, it would be best if this repo used the same variable name as the Sauce docs, but only @jmreidy has control over that.

**Comment by gvas** [comment]
That's true, but it seems like a typo. Especially in the light of #33

**Comment by gvas** [comment]
After looking at the travis build logs once again, I have realized that the access key is indeed intended to be in SAUCE_ACCESSKEY. I have rolled back test/sanity.js's changes, sorry.

**Comment by jmreidy** [comment]
Published in `2.2.0`.

**Pull request merged**
