### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by jdalton**
Update dependencies, especially Request.

image

### CODE REVIEW

**Comment by jdalton** [comment]
Boo test fails :ghost:

**Comment by jdalton** [comment]
It appears unit tests fail regardless of changes. I made the commit an empty one and still tests fail which mean you've got other issues to tackle.

**Comment by jdalton** [comment]
Ping. Any ideas on the test fails?

**Comment by jdalton** [comment]
So this project is dead?

**Comment by jdalton** [comment]
@Jonahss  Any ideas of a replacement for sauce-tunnel?
The maintainer is no longer responsive and the project appears abandoned.

**Comment by Jonahss** [comment]
Uhoh.
Thanks for the ping @jdalton. Perhaps we can get the repo transferred to us.

@jmreidy are you willing to transfer ownership, or grant someone push permissions and npm publish permissions?

**Comment by jmreidy** [comment]
Huh - for some reason I wasn't getting notifications on this (including from @jdalton 11 hours ago), but I DID just receive the notifcation from @Jonahss. I may have to update my GH email prefs... 

In the meantime - are these versions still good or should we update them even further? In the meantime I'll merge this PR.

**Comment by jdalton** [comment]
@jmreidy Huzzah!

The updates should have removed the vulnerable deps but there have been updates after.
Something like [greenkeeper.io](http://greenkeeper.io/) can help track that.

**Comment by jmreidy** [comment]
While I'm here - what's the standard for testing for Node libs these days? 0.8 and 0.10 is silly.

**Comment by jdalton** [comment]
0.10 still the most used version in production but I make it my oldest tested then I go 0.10, 0.12, 4, & 5.

**Comment by jmreidy** [comment]
@jdalton This is on master for now. I setup Greenkeeper and am waiting to release on NPM until I have updates for the remaining deps - so it'll be going out tomorrow. Thanks!

**Comment by jmreidy** [comment]
Released as 2.4.0.

**Comment by jdalton** [comment]
Awesome!

**Comment by jdalton** [comment]
Thank you!

**Pull request merged**
