### PR TITLE
Update Sauce Connect to v4.3.6

### PR DESCRIPTION
**Pull request by woollybogger**
Update Sauce Connect to the latest version.
Tested on all 3 platforms (not that I can prove it, but I did it).

### CODE REVIEW

**Comment by jmreidy** [comment]
@woollybogger PR testing has always had issues with this project. Shouldn't the secure travis env vars be used for all builds, even branch builds?

In the meantime, I'll test manually and push this out. Thanks!

**Comment by woollybogger** [comment]
@jmreidy Travis doesn't export secure environment variables for PR tests (otherwise people could write code that exposes and/or steals those values).

Using [Savage](https://github.com/twbs/savage) is a possible solution, but might be overkill. Perhaps implementing a PR life cycle like [the one grunt-saucelabs has](https://github.com/axemclion/grunt-saucelabs/blob/master/CONTRIBUTING.md#the-pull-request-lifecycle) would be better?

**Comment by jmreidy** [comment]
The grunt-saucelabs lifecycle seems perfect. I'll implement that today or
tomorrow. Thanks for pointing that out!

**Comment by woollybogger** [comment]
No problem :smiley:

**Comment by jmreidy** [comment]
Published as 2.1.6

**Pull request merged**
